<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ page import="com.cleaninginventory.model.User" %>
<%@ page import="com.cleaninginventory.model.Report" %>
<%@ page import="java.util.List" %>
<%
    User user = (User) session.getAttribute("user");
    if (user == null) {
        response.sendRedirect(request.getContextPath() + "/login.jsp");
        return;
    }

    String reportTitle = (String) request.getAttribute("reportTitle");
    String reportDescription = (String) request.getAttribute("reportDescription");
    String reportType = (String) request.getAttribute("reportType");
%>
<!DOCTYPE html>
<html>
<head>
    <title><%= reportTitle %> - Cleaning Inventory System</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; background-color: #f4f4f4; }
        .container { max-width: 1200px; margin: 0 auto; background: white; padding: 20px; border-radius: 8px; box-shadow: 0 0 10px rgba(0,0,0,0.1); }
        .header { display: flex; justify-content: space-between; align-items: center; border-bottom: 2px solid #eee; padding-bottom: 15px; margin-bottom: 20px; }
        .header h2 { color: #2c3e50; margin: 0; }
        .header a { color: white; background: #e74c3c; padding: 5px 15px; text-decoration: none; border-radius: 4px; font-size: 14px; }
        .header a:hover { background: #c0392b; }
        .header .back-btn { background: #3498db; }
        .header .back-btn:hover { background: #2980b9; }
        .header .print-btn { background: #27ae60; }
        .header .print-btn:hover { background: #219a52; }
        .report-info { background: #ecf0f1; padding: 15px; border-radius: 4px; margin-bottom: 20px; }
        .report-info p { margin: 5px 0; }
        .report-info .date { color: #7f8c8d; font-size: 12px; }
        table { width: 100%; border-collapse: collapse; margin-top: 15px; }
        th, td { border: 1px solid #ddd; padding: 10px; text-align: left; }
        th { background: #2c3e50; color: white; }
        tr:hover { background: #f5f5f5; }
        .no-data { text-align: center; color: #7f8c8d; padding: 20px; }
        .low-stock { color: red; font-weight: bold; }
        .status-badge { display: inline-block; padding: 3px 10px; border-radius: 12px; font-size: 12px; font-weight: bold; }
        .status-low { background: #f8d7da; color: #721c24; }
        .status-ok { background: #d4edda; color: #155724; }
        .footer { text-align: center; color: #7f8c8d; font-size: 12px; margin-top: 30px; padding-top: 15px; border-top: 1px solid #ecf0f1; }
        @media print { .no-print { display: none; } }
    </style>
</head>
<body>

<div class="container">
    <div class="header no-print">
        <h2><%= reportTitle %></h2>
        <div>
            <a href="${pageContext.request.contextPath}/reports" class="back-btn">← Back to Reports</a>
            <a href="#" class="print-btn" onclick="window.print()">🖨Print</a>
            <a href="${pageContext.request.contextPath}/LogoutServlet">Logout</a>
        </div>
    </div>

    <div class="report-info">
        <p><strong>Report:</strong> <%= reportTitle %></p>
        <p><%= reportDescription %></p>
        <p class="date">Generated on: <%= new java.util.Date() %></p>
        <p class="date">Generated by: <%= user.getFullName() %> (<%= user.getRole() %>)</p>
    </div>

    <table>
        <thead>
            <tr>
                <%
                    if ("inventory".equals(reportType) || "lowstock".equals(reportType)) {
                %>
                    <th>ID</th>
                    <th>Material Name</th>
                    <th>Category</th>
                    <th>Quantity</th>
                    <th>Unit</th>
                    <th>Threshold</th>
                    <th>Status</th>
                <%
                    } else if ("issuance".equals(reportType)) {
                %>
                    <th>ID</th>
                    <th>Material</th>
                    <th>Cleaner</th>
                    <th>Quantity</th>
                    <th>Issue Date</th>
                    <th>Status</th>
                <%
                    } else if ("usage".equals(reportType)) {
                %>
                    <th>Material Name</th>
                    <th>Total Issued</th>
                    <th>Remaining Stock</th>
                    <th>Unit</th>
                    <th>Usage Rate</th>
                <%
                    }
                %>
            </tr>
        </thead>
        <tbody>
            <%
                if ("inventory".equals(reportType) || "lowstock".equals(reportType)) {
                    List<Report.InventoryItem> items = (List<Report.InventoryItem>) request.getAttribute("reportData");
                    if (items != null && !items.isEmpty()) {
                        for (Report.InventoryItem item : items) {
                            boolean isLowStock = "Low Stock".equals(item.getStatus());
            %>
            <tr>
                <td><%= item.getMaterialId() %></td>
                <td><%= item.getMaterialName() %></td>
                <td><%= item.getCategory() != null ? item.getCategory() : "" %></td>
                <td class="<%= isLowStock ? "low-stock" : "" %>"><%= item.getQuantityInStock() %></td>
                <td><%= item.getUnit() != null ? item.getUnit() : "" %></td>
                <td><%= item.getLowStockThreshold() %></td>
                <td>
                    <span class="status-badge <%= isLowStock ? "status-low" : "status-ok" %>">
                        <%= item.getStatus() %>
                    </span>
                </td>
            </tr>
            <%
                        }
                    } else {
            %>
            <tr><td colspan="7" class="no-data">No data available for this report.</td></tr>
            <%
                    }
                } else if ("issuance".equals(reportType)) {
                    List<Report.IssuanceItem> items = (List<Report.IssuanceItem>) request.getAttribute("reportData");
                    if (items != null && !items.isEmpty()) {
                        for (Report.IssuanceItem item : items) {
            %>
            <tr>
                <td><%= item.getIssuanceId() %></td>
                <td><%= item.getMaterialName() != null ? item.getMaterialName() : "N/A" %></td>
                <td><%= item.getCleanerName() != null ? item.getCleanerName() : "N/A" %></td>
                <td><%= item.getQuantity() %></td>
                <td><%= item.getIssueDate() %></td>
                <td><%= item.getStatus() != null ? item.getStatus() : "Completed" %></td>
            </tr>
            <%
                        }
                    } else {
            %>
            <tr><td colspan="6" class="no-data">No issuance records found.</td></tr>
            <%
                    }
                } else if ("usage".equals(reportType)) {
                    List<Report.MaterialUsageItem> items = (List<Report.MaterialUsageItem>) request.getAttribute("reportData");
                    if (items != null && !items.isEmpty()) {
                        for (Report.MaterialUsageItem item : items) {
                            int usageRate = item.getTotalIssued() + item.getRemainingStock() > 0 ?
                                (int)((double)item.getTotalIssued() / (item.getTotalIssued() + item.getRemainingStock()) * 100) : 0;
            %>
            <tr>
                <td><%= item.getMaterialName() %></td>
                <td><%= item.getTotalIssued() %></td>
                <td><%= item.getRemainingStock() %></td>
                <td><%= item.getUnit() != null ? item.getUnit() : "" %></td>
                <td>
                    <div style="background: #ecf0f1; border-radius: 4px; height: 20px; width: 100%;">
                        <div style="background: #3498db; height: 100%; width: <%= usageRate %>%; border-radius: 4px; text-align: center; color: white; font-size: 11px; line-height: 20px;">
                            <%= usageRate %>% Used
                        </div>
                    </div>
                </td>
            </tr>
            <%
                        }
                    } else {
            %>
            <tr><td colspan="5" class="no-data">No usage data available.</td></tr>
            <%
                    }
                }
            %>
        </tbody>
    </table>

    <div class="footer">
        <p>Cleaning Inventory System - University Management &copy; 2026</p>
        <p>Report generated: <%= new java.util.Date() %></p>
    </div>
</div>

</body>
</html>